#! /bin/sh

# workspaces
bspc monitor -d I II III IV V VI

# ----- | bspc-rules | ----- #
bspc rule -a Pavucontrol state=floating rectangle=900x500+0+0 center=true
bspc rule -a Chromium desktop='^2'
bspc rule -a Viewnior state=floating
bspc rule -a Lxappearance state=floating center=true
bspc rule -a Alacritty rectangle=780x460+0+0 center=true
bspc rule -a Screenkey manage=off

# ----- | bspc-config | ----- #
bspc config border_width          2
bspc config window_gap            12
bspc config split_ratio           0.5
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true
#theme
bspc config focused_border_color "#1b1f20"
bspc config presel_feedback_color "#d8b4bd"


bspc config top_padding 0
bspc config left_padding 45
bspc config right_padding 0
bspc config bottom_padding 0

# ----- | autostart | ----- #
pgrep -x sxhkd > /dev/null || sxhkd &
nm-applet &
feh --bg-scale  ~/Pictures/Wallpapers/spacemanpink.png &
play-with-mpv &
picom &
killall lxsession ; lxsession &
killall xob ; python pulse-volume-watcher.py | xob &
killall tint2 ; tint2 &
pkill 2bspwm ; 2bspwm &
sh hello.sh &
